Repository spellshift/realm, pull requests merged in 2024-01, with the labels that each got.

#402 add unique name selection and opportunistically generate lower comple…
  tavern/internal/c2/server.go
  tavern/internal/ent/schema/beacon.go
  tavern/internal/namegen/namegen.go
  tavern/internal/namegen/namegen_test.go
  tavern/test_data.go
Labels: tavern

#454 Cp host view
  tavern/internal/www/build/asset-manifest.json
  tavern/internal/www/build/index.html
  tavern/internal/www/build/static/css/main.48904a80.css
  tavern/internal/www/build/static/css/main.48904a80.css.map
  tavern/internal/www/build/static/css/main.80f11433.css
  tavern/internal/www/build/static/css/main.80f11433.css.map
  tavern/internal/www/build/static/js/main.56c8afe2.js.LICENSE.txt
  tavern/internal/www/build/static/js/main.a0c00c89.js.LICENSE.txt
  tavern/internal/www/src/App.tsx
  tavern/internal/www/src/components/BeaconTile.tsx
  tavern/internal/www/src/components/HostTile.tsx
  tavern/internal/www/src/components/TaskTable.tsx
  tavern/internal/www/src/components/beacon-filter-bar/BeaconFilterBar.tsx
  tavern/internal/www/src/components/page-wrapper/PageWrapper.tsx
  tavern/internal/www/src/components/tavern-base-ui/DebouncedFreeTextSearch.tsx
  tavern/internal/www/src/context/TagContext.tsx
  tavern/internal/www/src/hooks/useTasks.ts
  tavern/internal/www/src/pages/create-quest/components/BeaconStep.tsx
  tavern/internal/www/src/pages/create-quest/components/BeaconStepWrapper.tsx
  tavern/internal/www/src/pages/create-quest/hooks/useBeaconFilter.ts
  tavern/internal/www/src/pages/host-details/HostDetails.tsx
  tavern/internal/www/src/pages/host-details/components/EditableHostHeader.tsx
  tavern/internal/www/src/pages/host-details/components/HostContent.tsx
  tavern/internal/www/src/pages/host-details/components/HostStatistics.tsx
  tavern/internal/www/src/pages/host-details/components/HostTasks.tsx
  tavern/internal/www/src/pages/host-list/HostList.tsx
  tavern/internal/www/src/pages/host-list/components/HostFilter.tsx
  tavern/internal/www/src/pages/host-list/components/HostTable.tsx
  tavern/internal/www/src/pages/host-list/hooks/useHostsFilter.ts
  tavern/internal/www/src/pages/host-list/hooks/useHostsTable.ts
  tavern/internal/www/src/pages/quest-list/components/QuestTable.tsx
  tavern/internal/www/src/pages/tasks/EditablePageHeader.tsx
  tavern/internal/www/src/pages/tasks/FilterBar.tsx
  tavern/internal/www/src/pages/tasks/FreeTextSearch.tsx
  tavern/internal/www/src/pages/tasks/Tasks.tsx
  tavern/internal/www/src/pages/tasks/useTasks.ts
  tavern/internal/www/src/utils/consts.ts
  tavern/internal/www/src/utils/enums.ts
  tavern/internal/www/src/utils/queries.ts
  tavern/internal/www/src/utils/utils.ts
  tavern/test_data.go
Labels: enhancement, Frontend

#502 GitHub Actions: Correct release type for building images
  .github/workflows/docker.yml
Labels: bug, dev-ops
