Repository spellshift/realm, pull requests merged in 2024-04, with the labels that each got.

#749 Don't disable apis on disable.
  terraform/main.tf
Labels: dev-ops

#751 Make platform values from `sys.get_os` more consistent with backend values.
  implants/lib/eldritch/src/sys/get_os_impl.rs
Labels: eldritch

#755 fix(host-details): Change from accordion to tab
  tavern/internal/www/build/asset-manifest.json
  tavern/internal/www/build/index.html
  tavern/internal/www/build/static/css/main.0de78947.css
  tavern/internal/www/build/static/css/main.0de78947.css.map
  tavern/internal/www/build/static/css/main.302d2dcd.css
  tavern/internal/www/build/static/css/main.302d2dcd.css.map
  tavern/internal/www/build/static/js/main.631df54b.js
  tavern/internal/www/build/static/js/main.631df54b.js.LICENSE.txt
  tavern/internal/www/build/static/js/main.685017a5.js
  tavern/internal/www/build/static/js/main.685017a5.js.LICENSE.txt
  tavern/internal/www/src/features/task-output/ErrorWrapper.tsx
  tavern/internal/www/src/features/task-output/ExpandedDetails.tsx
  tavern/internal/www/src/features/task-output/ShellTable.tsx
  tavern/internal/www/src/features/task-output/TaskOutput.tsx
  tavern/internal/www/src/features/task-output/index.tsx
  tavern/internal/www/src/pages/host-details/HostDetails.tsx
  tavern/internal/www/src/pages/host-details/components/BeaconAccordion.tsx
  tavern/internal/www/src/pages/host-details/components/BeaconTableWrapper.tsx
  tavern/internal/www/src/pages/host-details/components/HostContent.tsx
  tavern/internal/www/src/pages/host-details/components/HostStatistics.tsx
  tavern/internal/www/src/pages/host-details/components/HostTasks.tsx
Labels: Frontend
